name: PR merge workflow
on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    # - name: Run ESLint
    #   run: npm run lint

    - name: Run unit/integration tests
      run: npm run test

    - name: Run ESLint
      run: npm run test:bdd 